datasets:
  size:
    - 224
    - 224
  modality: "MRI"
  organ: "stomach"
  batch_size: 128
  root_dir: "/home/yliu/datasets/mediseg/bioparse/amos22"
  name: "bioparse_image" # "bioparse_image" 
  train_rate: 0.8
  featuremap_size: 7
  train:
    name: "${datasets.name}"
    modality: "${datasets.modality}"
    organ: "${datasets.organ}"
    root_dir: "${datasets.root_dir}"
    split: "train"
    train_rate: "${datasets.train_rate}"
    image_size: "${datasets.size}"
    featuremap_size: "${datasets.featuremap_size}"
  val:
    name: "${datasets.name}"
    modality: "${datasets.modality}"
    organ: "${datasets.organ}"
    root_dir: "${datasets.root_dir}"
    split: "val"
    train_rate: "${datasets.train_rate}"
    image_size: "${datasets.size}"
    featuremap_size: "${datasets.featuremap_size}"
  test:
    name: "${datasets.name}"
    modality: "${datasets.modality}"
    organ: "${datasets.organ}"
    root_dir: "${datasets.root_dir}"
    split: "test"
    train_rate: "${datasets.train_rate}"
    image_size: "${datasets.size}"
    featuremap_size: "${datasets.featuremap_size}"
 

model:
  clip:
    pretrain: "BiomedCLIP"
    num_concepts: 128
    inter_mode: False 


trainer:
  learning_rate: 1.0e-4
  output: "output_logs" # experiments/exp_name/logs 
  use_ema: False
  checkpoint_name: "best.pth" # the name of the loaded checkpoint "best.pth"
  num_epoch: 100
  save_interval: 20
  valiation_interval: 1
  sum_for_last: True
  gamma: 0.98 # the gamma of the Exp learning rate scheduler, normally 0.9~0.99
  alpha: 0.
  beta: 0.
  temperature: 100
  with_sigmoid: True
  gradient_accumulation_steps: 1
  clip_grads:


log_method: "wandb" # wandb, tensorboard

cbm_produce:
  train_dir: "${datasets.root_dir}/${datasets.modality}/train_cbm"
  val_dir: "${datasets.root_dir}/${datasets.modality}/train_cbm"
  test_dir: "${datasets.root_dir}/${datasets.modality}/test_cbm"