datasets:
  size:
    - 224
    - 224
  view: "4CH"
  organ: "left+heart+atrium"
  batch_size: 80
  root_dir: "/home/yliu/datasets/mediseg/bioparse/CAMUS"
  name: "bioparse_camus_view" # "bioparse_image"
  train_rate: 1.0
  featuremap_size: 28
  gcam_dir: "gcam_aug"
  train:
    name: "${datasets.name}"
    view: "${datasets.view}"
    organ: "${datasets.organ}"
    root_dir: "${datasets.root_dir}"
    split: "train"
    train_rate: "${datasets.train_rate}"
    image_size: "${datasets.size}"
    featuremap_size: "${datasets.featuremap_size}"
    gcam_dir: "${datasets.gcam_dir}"
  # val:
  #   name: "${datasets.name}"
  #   view: "${datasets.view}"
  #   organ: "${datasets.organ}"
  #   root_dir: "${datasets.root_dir}"
  #   split: "val"
  #   train_rate: "${datasets.train_rate}"
  #   image_size: "${datasets.size}"
  #   featuremap_size: "${datasets.featuremap_size}"
  #   gcam_dir: "${datasets.gcam_dir}"
  test:
    name: "${datasets.name}"
    view: "${datasets.view}"
    organ: "${datasets.organ}"
    root_dir: "${datasets.root_dir}"
    split: "test"
    train_rate: "${datasets.train_rate}"
    image_size: "${datasets.size}"
    featuremap_size: "${datasets.featuremap_size}"
    gcam_dir: "${datasets.gcam_dir}"
 

model:
  clip:
    pretrain: "PMC_CLIP"
    num_concepts: 128
    inter_mode: False 
    no_proj: True
    one_layer: True
    task: "cbm"


trainer:
  learning_rate: 1.0e-4
  output: "output_logs" # experiments/exp_name/logs 
  use_ema: False
  checkpoint_name: "best.pth" # the name of the loaded checkpoint "best.pth"
  num_epoch: 100
  save_interval: 20
  valiation_interval: 1
  sum_for_last: True
  gamma: 0.98 # the gamma of the Exp learning rate scheduler, normally 0.9~0.99
  alpha: 0.
  beta: 0.
  temperature: 100
  with_sigmoid: True
  gradient_accumulation_steps: 1
  clip_grads:
  augmentation: True

log_method: "wandb" # wandb, tensorboard

cbm_produce:
  train_dir: "${datasets.root_dir}/train_cbm_aug"
  val_dir:
  test_dir: "${datasets.root_dir}/test_cbm_aug"