datasets:
  batch_size: 4
  train:
    name: "isic_seg"
    prompt_type: "p6"
    images_dir: "/data/claude/datasets/medisegs/ISIC/Train/ISBI2016_ISIC_Part1_Training_Data"
    masks_dir: "/data/claude/datasets/medisegs/ISIC/Train/ISBI2016_ISIC_Part1_Training_GroundTruth"
    caps_file: "/data/claude/datasets/medisegs/ISIC/anns/train.json"
    override_prompt:
    zero_prompt: False
  val:
    name: "isic_seg"
    prompt_type: "p6"
    images_dir: "/data/claude/datasets/medisegs/ISIC/Train/ISBI2016_ISIC_Part1_Training_Data"
    masks_dir: "/data/claude/datasets/medisegs/ISIC/Train/ISBI2016_ISIC_Part1_Training_GroundTruth"
    caps_file: "/data/claude/datasets/medisegs/ISIC/anns/val.json"
    override_prompt:
    zero_prompt: False
  test:
    name: "isic_seg"
    prompt_type: "p6"
    images_dir: "/data/claude/datasets/medisegs/ISIC/Test/ISBI2016_ISIC_Part1_Test_Data"
    masks_dir: "/data/claude/datasets/medisegs/ISIC/Test/ISBI2016_ISIC_Part1_Test_GroundTruth"
    caps_file: "/data/claude/datasets/medisegs/ISIC/anns/test.json"
    override_prompt:
    zero_prompt: False