datasets:
  batch_size: 4
  train:
    name: "isic_seg"
    prompt_type: "p6"
    # images_dir: "/home/yliu/datasets/mediseg/ISIC/Train/ISBI2016_ISIC_Part1_Training_Data"
    images_dir: "/data/claude/datasets/medisegs/ISIC/Train/ISBI2016_ISIC_Part1_Training_Data"
    # masks_dir: "/home/yliu/datasets/mediseg/ISIC/Train/ISBI2016_ISIC_Part1_Training_GroundTruth"
    masks_dir: "/data/claude/datasets/medisegs/ISIC/Train/ISBI2016_ISIC_Part1_Training_GroundTruth"
    sdf_dir: "/data/claude/datasets/medisegs/ISIC/Train/ISBI2016_ISIC_Part1_Training_GroundTruth_USDF"
    # caps_file: "/home/yliu/datasets/mediseg/ISIC/anns/train.json"
    caps_file: "/data/claude/datasets/medisegs/ISIC/anns/train.json"
    override_prompt:
    zero_prompt: False
  val:
    name: "isic_seg"
    prompt_type: "p6"
    # images_dir: "/home/yliu/datasets/mediseg/ISIC/Train/ISBI2016_ISIC_Part1_Training_Data"
    images_dir: "/data/claude/datasets/medisegs/ISIC/Train/ISBI2016_ISIC_Part1_Training_Data"
    # masks_dir: "/home/yliu/datasets/mediseg/ISIC/Train/ISBI2016_ISIC_Part1_Training_GroundTruth"
    masks_dir: "/data/claude/datasets/medisegs/ISIC/Train/ISBI2016_ISIC_Part1_Training_GroundTruth"
    sdf_dir: "/data/claude/datasets/medisegs/ISIC/Train/ISBI2016_ISIC_Part1_Training_GroundTruth_USDF"
    # caps_file: "/home/yliu/datasets/mediseg/ISIC/anns/val.json"
    caps_file: "/data/claude/datasets/medisegs/ISIC/anns/val.json"
    override_prompt:
    zero_prompt: False
  test:
    name: "isic_seg"
    prompt_type: "p6"
    # images_dir: "/home/yliu/datasets/mediseg/ISIC/Test/ISBI2016_ISIC_Part1_Test_Data"
    images_dir: "/data/claude/datasets/medisegs/ISIC/Test/ISBI2016_ISIC_Part1_Test_Data"
    # masks_dir: "/home/yliu/datasets/mediseg/ISIC/Test/ISBI2016_ISIC_Part1_Test_GroundTruth"
    masks_dir: "/data/claude/datasets/medisegs/ISIC/Test/ISBI2016_ISIC_Part1_Test_GroundTruth"
    sdf_dir: "/data/claude/datasets/medisegs/ISIC/Test/ISBI2016_ISIC_Part1_Test_GroundTruth_USDF"
    # caps_file: "/home/yliu/datasets/mediseg/ISIC/anns/test.json"
    caps_file: "/data/claude/datasets/medisegs/ISIC/anns/test.json"
    override_prompt:
    zero_prompt: False

model:
  clip:
    pretrain: "ViT-B-32" # Pubmedclip, MedICaT, ViT-B-32
    outlayers: 
      # - 2
      # - 5
      # - 8
      - 11
  diffusion:
    image_size: 224
    in_channels: 4 # 4 for ISIC
    num_channels: 128
    out_channels: 2
    num_res_blocks: 2
    attention_resolutions: "16"
    dropout: 0.0
    channel_mult: ""
    num_classes:
    use_checkpoint: False
    use_fp16: False
    num_heads: 1
    num_head_channels: -1
    num_heads_upsample: -1
    use_scale_shift_norm: -1
    resblock_updown: False
    use_new_attention_order: False
    condition: "high_way"

trainer:
  learning_rate: 1.0e-4
  output: "output_logs" # experiments/exp_name/logs 
  use_ema: False
  checkpoint_name: checkpoint_iter100000.pth # the name of the loaded checkpoint
  num_timesteps: 1000
  num_iterations: 100000
  save_interval: 100

log_method: "wandb" # wandb, tensorboard