datasets:
  batch_size: 8
  size:
  inter_layer: "layer11"
  basedir: "/data/claude/datasets/medisegs/ISIC"
  train:
    name: "isic_seg"
    prompt_type: "p6"
    images_dir: "${datasets.basedir}/Train/ISBI2016_ISIC_Part1_Training_Data"
    masks_dir: "${datasets.basedir}/Train/ISBI2016_ISIC_Part1_Training_GroundTruth"
    sdf_dir: "${datasets.basedir}/Train/ISBI2016_ISIC_Part1_Training_GroundTruth_USDF"
    inter_dir: "${datasets.basedir}/Train/ISBI2016_ISIC_Part1_Training_LRP/Pubmedclip/LRP"
    caps_file: "${datasets.basedir}/anns/train.json"
    inter_layer: "${datasets.inter_layer}"
    override_prompt:
    image_size: "${datasets.size}"
  val:
    name: "isic_seg"
    prompt_type: "p6"
    images_dir: "${datasets.basedir}/Train/ISBI2016_ISIC_Part1_Training_Data"
    masks_dir: "${datasets.basedir}/Train/ISBI2016_ISIC_Part1_Training_GroundTruth"
    sdf_dir: "${datasets.basedir}/Train/ISBI2016_ISIC_Part1_Training_GroundTruth_USDF"
    inter_dir: "${datasets.basedir}/Train/ISBI2016_ISIC_Part1_Training_LRP/Pubmedclip/LRP"
    caps_file: "${datasets.basedir}/anns/val.json"
    inter_layer: "${datasets.inter_layer}"
    override_prompt:
    image_size: "${datasets.size}"
  test:
    name: "isic_seg"
    prompt_type: "p6"
    images_dir: "${datasets.basedir}/Test/ISBI2016_ISIC_Part1_Test_Data"
    masks_dir: "${datasets.basedir}/Test/ISBI2016_ISIC_Part1_Test_GroundTruth"
    sdf_dir: "${datasets.basedir}/Test/ISBI2016_ISIC_Part1_Test_GroundTruth_USDF"
    inter_dir: "${datasets.basedir}/Test/ISBI2016_ISIC_Part1_Test_LRP/Pubmedclip/LRP"
    caps_file: "${datasets.basedir}/anns/test.json"
    inter_layer: "${datasets.inter_layer}"
    override_prompt:
    image_size: "${datasets.size}"

model:
  clip:
    pretrain: "Pubmedclip" # Pubmedclip, MedICaT, ViT-B-32
    outlayers: 
      - 11
    inter_mode: False # get RLP from dataset/ clip 
    proj_patch: True
  diffusion:
    version: "v1"
    image_size: 224
    in_channels: 4    # 1 for CAM input only and image input only as condition
    condition_channels: 4
    num_channels: 128
    out_channels: 1
    num_res_blocks: 2
    attention_resolutions: "16"
    dropout: 0.0
    channel_mult: ""
    num_classes: # set None for avoid label embeddings (why we have it, strange ???)
    use_checkpoint: True
    use_fp16: False
    num_heads: 1
    num_head_channels: -1
    num_heads_upsample: -1
    use_scale_shift_norm: -1
    resblock_updown: False
    use_new_attention_order: False

trainer:
  gt_type: "sdf_map" # sdf_map, mask
  learning_rate: 1.0e-4
  output: "output_logs" # experiments/exp_name/logs 
  use_ema: False
  checkpoint_name: # the name of the loaded checkpoint
  num_timesteps: 1000
  num_iterations: 100000
  save_interval: 100
  start_point: "all" 
  gradient_accumulation_steps: 1
  clip_grads:

log_method: "wandb" # wandb, tensorboard